apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ms-1
  template:
    metadata:
      labels:
        app: ms-1
    spec:
      containers:
        - name: ms-1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
